name: Create issue on file change
on:
  push:
    branches:
      - dev
    paths:
      - public/install-popup-button.js
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run GitHub CLI command
        run: |
          gh issue create --repo alvarobyrne/actions-test --title "File changed" --body "File changed"